# Generated by Django 5.2.2 on 2025-10-26 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu', models.CharField(choices=[('main', 'Main dishes'), ('breakfast', 'Breakfast'), ('side_dish', 'Side dishes'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], default='main', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]
