# Generated by Django 5.2.2 on 2025-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
