# Generated by Django 5.2.2 on 2025-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_item_image_item_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_name',
            field=models.ImageField(default='', upload_to='dishes/'),
            preserve_default=False,
        ),
    ]
