# Generated by Django 5.2.2 on 2025-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_item_description_alter_item_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
